# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:11.0
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - run:
          name: setup
          command: source <(curl -s https://raw.githubusercontent.com/boxheed/shippable-scripts/master/java-build-ci-setup)
      - checkout
      - run: ./gradlew clean build
  
  security:
    docker:
      # specify the version you desire here
      - image: boxheed/openjdk-17-nvd-cve-db:latest
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - run:
          name: setup
          command: source <(curl -s https://raw.githubusercontent.com/boxheed/shippable-scripts/master/java-build-ci-setup)
      - checkout
      - run: ./gradlew clean dependencyCheckAnalyze

  security-2:
    docker:
      - image: cimg/openjdk:11.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: cd /tmp && curl https://github.com/google/osv-scanner/releases/download/v1.6.2/osv-scanner_1.6.2_linux_amd64 -o osv-scanner && chmod +x /tmp/osv-scanner
      - run: ./gradlew --write-locks resolveAndLockAl
      - run: ls -al && pwd && /tmp/osv-scanner -r `pwd`

  release:
    docker:
      # specify the version you desire here
      - image: boxheed/openjdk-17-nvd-cve-db:latest
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - run:
          name: setup
          command: source <(curl -s https://raw.githubusercontent.com/boxheed/shippable-scripts/master/java-build-ci-setup)
      - checkout
      - run: ./gradlew createRelease
      - run: git push --tags

  publish:
    docker:
      # specify the version you desire here
      - image: boxheed/openjdk-17-nvd-cve-db:latest
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - run:
          name: setup
          command: source <(curl -s https://raw.githubusercontent.com/boxheed/shippable-scripts/master/java-build-ci-setup)
      - checkout
      - run: ./gradlew build publish githubRelease

workflows:
  build:
    jobs:
      - build:
          context: boxhead-builds
      - security:
          context: boxhead-builds
      - security-2:
          context: boxhead-builds
      - release:
          context: boxhead-builds
          requires:
            - build
            - security
          filters:
            branches:
              only: /^(?:main|master)$/
      - publish:
          context: boxhead-builds
          filters:
            # only act on version tags
            branches:
              ignore: /.*/
            tags:
              only: /^release-\d+\.\d+\.\d+$/